on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: ["**"]

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    container: greyltc/archlinux-aur:paru
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make mingw-w64 && aur-install mingw-w64-lua51"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -DIS_CI=1 -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain.cmake && cmake --build . --config Release"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/
            !build/cmake
            !build/_deps
